
- name : variables
  hosts : localhost
  vars :
    course : " devops"
    trainer : "chandu"
    duration : "110hrs"
  tasks :
    - name : check variables
      ansible.builtin.debug: 
        msg : "Iam lesrning {{course}} from trainer {{trainer}} duration {{duration}}"


